project:
  type: website
  output-dir: docs
  resources:
    - static/images/
  

website:
  title: "Autonomous Navigation for the Polaris GEM e2"
  navbar:
    background: light
    left:
      - text: "Resources"
        menu:
          - text: "Schedule and Guidlines"
            href: https://safeautonomy-illinois.github.io/ece484-site/spring-2026/projects/robotaxi/


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
