project:
  type: website
  output-dir: docs

website:
  title: "Project Title"
  navbar:
    background: light
    left:
      - text: "Resources"
        menu:
          - text: "Schedule and Guidlines"
            href: https://safeautonomy-illinois.github.io/ece484-site/spring-2026/projects/robotaxi/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full